### ISSUE TITLE
vs code cannot stay connected to hub

### ISSUE THREAD

**Issue by JessicaS11** [ICESAT-2HackWeek/jupyter-image-2020#14]
As of Monday morning, the VS Code add-in cannot stay connected to the hub. A pop-up window says "Cannot Reconnect. Please reload the window" and gives options to cancel (in which case VS Code is present and seemingly functional but not connected to the hub) or reload the window (which reloads the VS Code tab and after a few seconds results in the same pop-up window). The problem is still recurring today. I'll note the bracketed text after VS Code in the JupyterHub launch window is not properly rendered. It happens both on aws-uswest2.pangeo.io and icesat-2.hackweek.io.

**Comment by scottyhq** [comment]
Thanks for pointing this out, I'll see what I can figure out to get it working again

**Comment by scottyhq** [comment]
seems there were some compatibility issues with the newly released code-server 3.4, so we've pinned back to 3.2 starting with the 2020.06.03 image.

**Comment by JessicaS11** [comment]
Gotcha. Thanks for pinning back to a working version!
